data:
    type: "LLdataset"
    train_dataset: "NH_HAZE"
    val_dataset: "LOLv1"
    patch_size: 512
    channels: 3
    num_workers: 4
    data_dir: "/opt/data/private/SJ/LPCDiff/"
    ckpt_dir: "ckpt/"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 400

training:
    batch_size: 4
    n_epochs: 50000
    validation_freq: 500

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0001
    amsgrad: False
    eps: 0.00000001
    step_size: 8000
    gamma: 0.8
